version: "3.9"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.30-debian
    restart: always
    environment:
      MYSQL_DATABASE: chatApp
      MYSQL_ROOT_PASSWORD: secret-pw
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2.7-alpine
    restart: always
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server --appendonly yes

  rabbitmq:
      image: rabbitmq:3.9-alpine
      restart: always
      volumes:
        - ./volumes/rabbitmq:/var/lib/rabbitmq

  elasticsearch:
      platform: linux/x86_64
      image: elasticsearch:5.6.16-alpine
      restart: always
      ports:
        - "9200:9200"
      volumes:
        - ./volumes/elastic:/usr/share/elasticsearch/data

  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./entrypoint.sh && rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - mysql
      - redis
      - elasticsearch
      - rabbitmq
    environment:
      - RAILS_ENV=production
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ELASTIC_HOST=elasticsearch
      - MYSQL_ROOT_PASSWORD=secret-pw
