version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: chatApp
      MYSQL_ROOT_PASSWORD: secret-pw
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    restart: always
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server --appendonly yes

  rabbit:
      image: rabbitmq:3.11.1-alpine
      restart: always
      volumes:
        - ./volumes/rabbitmq:/var/lib/rabbitmq


#  elasticsearch:
##      platform: linux/x86_64
#      image: elasticsearch:6.8.23
#      restart: always
#      ports:
#        - "9200:9200"
#      environment:
#        - bootstrap.memory_lock=true
#        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      volumes:
#        - ./volumes/elastic:/usr/share/elasticsearch/data

  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./entrypoint.sh && rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    depends_on:
      - db
      - redis
      - rabbit
    links:
      - db
      - redis
      - rabbit
    environment:
      - RAILS_ENV=production
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=secret-pw
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbit
#      - ELASTIC_HOST=elasticsearch

#  services:
#    platform: linux/x86_64
#    build: .
#    command: sh -c "rake sneakers:run"
#    restart: always
#    volumes:
#      - .:/app
#    links:
#      - mysql
#      - redis
#      - elasticsearch
#      - rabbitmq
#    depends_on:
#      - app
#    environment:
#      MYSQL_HOST: mysql
#      MYSQL_ROOT_PASSWORD: secret-pw
#      REDIS_HOST: redis
#      RABBITMQ_HOST: rabbitmq
#      ELASTIC_HOST: elasticsearch
