version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.30-debian
    restart: always
    environment:
      MYSQL_DATABASE: chatApp
      MYSQL_ROOT_PASSWORD: secret-pw
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2.7-alpine
    restart: always
    volumes:
      - ./volumes/redis-data:/data
    command: redis-server --appendonly yes

  rabbitmq:
      image: rabbitmq:3.9-alpine
      restart: always
      ports:
        - "5672:5672"
      volumes:
        - ./volumes/rabbitmq:/var/lib/rabbitmq

  elasticsearch:
      platform: linux/x86_64
      image: elasticsearch:5.6.16-alpine
      restart: always
      ports:
        - "9200:9200"
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      volumes:
        - ./volumes/elastic:/usr/share/elasticsearch/data

  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./entrypoint.sh && rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    links:
      - mysql
      - redis
      - elasticsearch
      - rabbitmq
    environment:
      - RAILS_ENV=production
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - ELASTIC_HOST=elasticsearch
      - MYSQL_ROOT_PASSWORD=secret-pw

  services:
    platform: linux/x86_64
    build: .
    command: sh -c "rake sneakers:run"
    restart: always
    volumes:
      - .:/app
    links:
      - mysql
      - redis
      - elasticsearch
      - rabbitmq
    depends_on:
      - app
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret-pw
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      ELASTIC_HOST: elasticsearch
